title: "Alicade Blog"
description: "Software Development | QA Engineering | Cloud"
author: "Alicade"

url: "https://alicade123.github.io"
baseurl: "/Part-III_skills---github---pages"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

google_analytics_id: "" # Add your GA4 ID, e.g. G-XXXXXXXXXX

collections:
  posts:
    output: true
