title: "Alicade Blog"
description: "Software Development | QA Engineering | Cloud"
author: "Alicade"
baseurl: "https://alicade123.github.io/Part-III_skills---github---pages/"
url: "https://Alicade123.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

collections:
  posts:
    output: true

